name: 🚀 Build & Deploy

on:
  push:
    branches: [main]
    tags:
      - 'v*'

env:
  ACR: ${{ vars.ACR_NAME }}.azurecr.io
  IMAGE: ${{ vars.ACR_NAME }}.azurecr.io/flask-app:${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - run: pip install -r requirements.txt
        working-directory: ./app

      - run: pytest
        working-directory: ./app

      - name: Build Docker image
        run: docker build -t flask-app:${{ github.sha }} .

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Login to ACR
        run: az acr login --name ${{ vars.ACR_NAME }}

      - name: Push Docker image
        run: |
          docker tag flask-app:${{ github.sha }} $IMAGE
          docker push $IMAGE

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Deploy to Web App for Containers
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          images: ${{ vars.ACR_NAME }}.azurecr.io/flask-app:${{ github.ref_name }} #$IMAGE

      # - name: Deploy to Web App
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: modus-create-app
      #     slot-name: production
      #     images: modusacr13543.azurecr.io/flask-app:main
