name: 🛠️ Infra Management - Terraform

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: "Set to true to destroy infrastructure"
        required: false
        default: "false"

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./deploy/terraform

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6
        terraform_wrapper: true

    - name: Terraform Init
      # working-directory: ./deploy/terraform
      run: terraform init
      env:
        ARM_CLIENT_ID: ${{ secrets.STATE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.STATE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.STATE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.STATE_TENANT_ID }}


    - name: Terraform Plan
      id: plan
      if: inputs.destroy != 'true'
      # working-directory: ./deploy/terraform
      run: |
          terraform plan \
          -var="resource_group_name=${{ vars.RESOURCE_GROUP }}" \
          -var="location=${{ vars.AZURE_LOCATION }}" \
          -var="prefix=flaskdemo" \
          -var="acr_name=${{ vars.ACR_NAME }}" \
          -var="webapp_name=${{ vars.AZURE_WEBAPP_NAME }}" \
          -var="infra_client_id=${{ secrets.ARM_CLIENT_ID }}" \
          -var="infra_client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
          -var="infra_subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
          -var="infra_tenant_id=${{ secrets.ARM_TENANT_ID }}"
      env:
        # TF_LOG: DEBUG
        ARM_CLIENT_ID: ${{ secrets.STATE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.STATE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.STATE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.STATE_TENANT_ID }}


    - name: Terraform Apply
      if: inputs.destroy != 'true'
      working-directory: ./deploy/terraform
      run: |
        terraform apply -auto-approve \
          -var="resource_group_name=${{ vars.RESOURCE_GROUP }}" \
          -var="location=${{ vars.AZURE_LOCATION }}" \
          -var="prefix=flaskdemo" \
          -var="acr_name=${{ vars.ACR_NAME }}" \
          -var="webapp_name=${{ vars.AZURE_WEBAPP_NAME }}" \
          -var="infra_client_id=${{ secrets.ARM_CLIENT_ID }}" \
          -var="infra_client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
          -var="infra_subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
          -var="infra_tenant_id=${{ secrets.ARM_TENANT_ID }}"
      env:
        # TF_LOG: DEBUG
        ARM_CLIENT_ID: ${{ secrets.STATE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.STATE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.STATE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.STATE_TENANT_ID }}

    - name: Terraform Destroy
      if: inputs.destroy == 'true'
      working-directory: ./deploy/terraform
      run: |
        terraform destroy -auto-approve \
          -var="resource_group_name=${{ vars.RESOURCE_GROUP }}" \
          -var="location=${{ vars.AZURE_LOCATION }}" \
          -var="prefix=flaskdemo" \
          -var="acr_name=${{ vars.ACR_NAME }}" \
          -var="webapp_name=${{ vars.AZURE_WEBAPP_NAME }}" \
          -var="infra_client_id=${{ secrets.ARM_CLIENT_ID }}" \
          -var="infra_client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
          -var="infra_subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
          -var="infra_tenant_id=${{ secrets.ARM_TENANT_ID }}"
      env:
        ARM_CLIENT_ID: ${{ secrets.STATE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.STATE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.STATE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.STATE_TENANT_ID }}
