name: Terraform Infra Control

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: "Set to true to destroy infrastructure"
        required: false
        default: "false"

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      working-directory: ./deploy/terraform
      run: terraform init

    - name: Terraform Plan
      if: inputs.destroy != 'true'
      working-directory: ./deploy/terraform
      run: terraform plan \
          -var="resource_group_name=${{ vars.RESOURCE_GROUP }}" \
          -var="location=${{ vars.AZURE_LOCATION }}" \
          -var="prefix=flaskdemo" \
          -var="acr_name=${{ vars.ACR_NAME }}" \
          -var="webapp_name=${{ vars.AZURE_WEBAPP_NAME }}" \
          -var="infra_subscription_id=${{ secrets.INFRA_SUBSCRIPTION_ID }}"


    - name: Terraform Apply
      if: inputs.destroy != 'true'
      working-directory: ./deploy/terraform
      run: terraform apply -auto-approve \
          -var="resource_group_name=${{ vars.RESOURCE_GROUP }}" \
          -var="location=${{ vars.AZURE_LOCATION }}" \
          -var="prefix=flaskdemo" \
          -var="acr_name=${{ vars.ACR_NAME }}" \
          -var="webapp_name=${{ vars.AZURE_WEBAPP_NAME }}" \
          -var="infra_subscription_id=${{ secrets.INFRA_SUBSCRIPTION_ID }}"

    - name: Terraform Destroy
      if: inputs.destroy == 'true'
      working-directory: ./deploy/terraform
      run: terraform destroy -auto-approve \
          -var="resource_group_name=${{ vars.RESOURCE_GROUP }}" \
          -var="location=${{ vars.AZURE_LOCATION }}" \
          -var="prefix=flaskdemo" \
          -var="acr_name=${{ vars.ACR_NAME }}" \
          -var="webapp_name=${{ vars.AZURE_WEBAPP_NAME }}" \
          -var="infra_subscription_id=${{ secrets.INFRA_SUBSCRIPTION_ID }}"
